
export interface ExcelMapping {
    excelHeader: string;
    dbField: string | null;
}

export interface MasterMapping {
    excelHeader: string;
    masterField: string;
}

export const PROFILE_MAPPING: ExcelMapping[] = [
    { excelHeader: 'NOMIR INDUK KARYAWAN', dbField: 'nomor_induk_karyawan' },
    { excelHeader: 'NAMA LENGKAP', dbField: 'nama_lengkap' },
    { excelHeader: 'POSISI JABATAN', dbField: 'posisi_jabatan' },
    { excelHeader: 'LOKASI COSTING', dbField: 'costing' },
    { excelHeader: 'ACTUAL', dbField: 'actual' },
    { excelHeader: 'ASSIGN', dbField: 'assign' },
    { excelHeader: 'PANGKAT KATEGORI', dbField: 'kategori_pangkat' },
    { excelHeader: 'GOLONGAN', dbField: 'golongan_pangkat' },
    { excelHeader: 'SUB GOLONGAN', dbField: 'sub_golongan_pangkat' },
    { excelHeader: 'TEMPAT LAHIR', dbField: 'tempat_lahir' },
    { excelHeader: 'TANGGAL LAHIR', dbField: 'tanggal_lahir' },
    { excelHeader: 'TANGGAL JOIN GROUP', dbField: 'tanggal_masuk' },
    { excelHeader: 'TANGGAL MASUK', dbField: 'tanggal_masuk_group' },
    { excelHeader: 'JENIS HUBUNGAN KERJA', dbField: 'jenis_hubungan_kerja' },
    { excelHeader: 'TANGGAL AWAL KONTRAK', dbField: 'tanggal_kontrak' },
    { excelHeader: 'TANGGAL AKHIR KONTRAK', dbField: 'tanggal_akhir_kontrak' },
    { excelHeader: 'TANGGAL TETAP', dbField: 'tanggal_permanent' },
    { excelHeader: 'TANGGAL KELUAR', dbField: 'tanggal_berhenti' },
    { excelHeader: 'JENIS KELAMIN', dbField: 'jenis_kelamin' },
    { excelHeader: 'AGAMA', dbField: 'agama' },
    { excelHeader: 'ALAMAT DOMISILI', dbField: 'alamat_domisili' },
    { excelHeader: 'KOTA DOMISILI', dbField: 'kota_domisili' },
    { excelHeader: 'PROPINSI DOMISILI', dbField: 'provinsi_domisili' },
    { excelHeader: 'NOMOR TELEPON RUMAH 1', dbField: 'nomor_telepon_rumah_1' },
    { excelHeader: 'NOMOR TELEPON RUMAJ 2', dbField: 'nomor_telepon_rumah_2' },
    { excelHeader: 'NOMOR HP 1', dbField: 'nomor_handphone' },
    { excelHeader: 'NOMOR JP 2', dbField: 'nomor_handphone_2' },
    { excelHeader: 'GOLOGAN DARAH', dbField: 'golongan_darah' },
    { excelHeader: 'NOMOR KTP', dbField: 'nomor_ktp' },
    { excelHeader: 'ALAMAT KTP', dbField: 'alamat_ktp' },
    { excelHeader: 'NOMOR NPWP', dbField: 'nomor_npwp' },
    { excelHeader: 'NOMOR BPJS-TK', dbField: 'nomor_bpjs' },
    { excelHeader: 'NOMOR DANA PENSIUN', dbField: 'no_dana_pensiun' },
    { excelHeader: 'NOMOR REKENING', dbField: 'nomor_rekening' },
    { excelHeader: 'NAMA PEMILIK REKENING', dbField: 'nama_pemegang_rekening' },
    { excelHeader: 'STATUS PERKAWINAN (PAJAK)', dbField: 'status_pajak' },
    { excelHeader: 'JUMLAH ANAK', dbField: 'jumlah_anak' },
    { excelHeader: 'STATUS PAJAK', dbField: null },
    { excelHeader: 'PENDIDIKAN TERAKHIR', dbField: 'tingkat_pendidikan' },
    { excelHeader: 'JURUSAN PENDIDIKAN', dbField: 'bidang_studi' },
    { excelHeader: 'NAMA SEKOLAH', dbField: 'nama_sekolah' },
    { excelHeader: 'KOTA SEKOLAH', dbField: 'kota_sekolah' },
    { excelHeader: 'STATUS PENDIDIKAN', dbField: 'status_kelulusan' },
    { excelHeader: 'KETERANGAN PENDIDIKAN', dbField: 'keterangan (**Group: Education**)' },
    { excelHeader: 'KODE PENDIDIKAN', dbField: null },
    { excelHeader: 'STATUS PERNIKAHAN', dbField: 'status_pernikahan' },
    { excelHeader: 'TANGGAL MENIKAH', dbField: 'tanggal_menikah' },
    { excelHeader: 'TANGGAL CERAI', dbField: 'tanggal_cerai' },
    { excelHeader: 'TANGGAL WAFAT PASANGAN', dbField: 'tanggal_wafat_pasangan' },
    { excelHeader: 'NAMA PASANGAN NIKAH', dbField: 'nama_pasangan*' },
    { excelHeader: 'TANGGAL LAHIR PASANGAN', dbField: 'tanggal_lahir_pasangan' },
    { excelHeader: 'PENDIDIKAN TERAKHIR PASANGAN', dbField: 'pendidikan_terakhir_pasangan' },
    { excelHeader: 'PEKERJAAN PASANGAN', dbField: 'pekerjaan_pasangan' },
    { excelHeader: 'KETERANGAN PASANGAN', dbField: 'keterangan_pasangan' },
    { excelHeader: 'NAMA ANAK 1', dbField: 'nama_anak_1' },
    { excelHeader: 'JENIS KELAMIN ANAK 1', dbField: 'jenis_kelamin_anak_1' },
    { excelHeader: 'TANGGAL LAHIR ANAK 1', dbField: 'tanggal_lahir_anak_1' },
    { excelHeader: 'KETERANGAN ANAK 1', dbField: 'keterangan_anak_1' },
    { excelHeader: 'NAMA ANAK 2', dbField: null },
    { excelHeader: 'JENIS KELAMIN ANAK 2', dbField: null },
    { excelHeader: 'TANGGAL LAHIR ANAK 2', dbField: null },
    { excelHeader: 'KETERANGAN ANAK 2', dbField: null },
    { excelHeader: 'NAMA ANAK 3', dbField: null },
    { excelHeader: 'JENIS KELAMIN ANAK 3', dbField: null },
    { excelHeader: 'TANGGAL LAHIR ANAK 3', dbField: null },
    { excelHeader: 'KETERANGAN ANAK 3', dbField: null },
    { excelHeader: 'NAMA ANAK 4', dbField: null },
    { excelHeader: 'JENIS KELAMIN ANAK 4', dbField: null },
    { excelHeader: 'TANGGAL LAHIR ANAK 4', dbField: null },
    { excelHeader: 'KETERANGAN ANAK 4', dbField: null },
    { excelHeader: 'NAMA BAPAK KANDUNG', dbField: null },
    { excelHeader: 'TANGGAL LAHUR BAPAK KANDUNG', dbField: null },
    { excelHeader: 'PENDIDIKAN TERAKHIR BAPAK KANDUNG', dbField: null },
    { excelHeader: 'PEKERJAAN BAPAK KANDUNG', dbField: null },
    { excelHeader: 'KETERANGAN BAPAK KANDUNG', dbField: null },
    { excelHeader: 'NAMA IBU KANDUNG', dbField: null },
    { excelHeader: 'TANGGAL LAHIR IBU KANDUNG', dbField: null },
    { excelHeader: 'PENDIDIKAN TERAKHIR IBU KANDUNG', dbField: null },
    { excelHeader: 'PEKERJAAN IBU KANDUNG', dbField: null },
    { excelHeader: 'KETERANGAN IBU KANDUNG', dbField: null },
    { excelHeader: 'NAMA SAUDARA KANDUNG 1', dbField: 'nama_saudara_kandung_1' },
    { excelHeader: 'JENIS KELELAMIN SAUDARA KANDUNG 1', dbField: 'jenis_kelamin_saudara_kandung_1' },
    { excelHeader: 'TANGGAL LAHUR SAUDARA KANDUNG 1', dbField: 'tanggal_lahir_saudara_kandung_1' },
    { excelHeader: 'PENDIDIKAN TERAKHIR SAUDARA KANDUNG 1', dbField: 'pendidikan_terakhir_saudara_kandung_1' },
    { excelHeader: 'PEKERJAAN SAUDARA KANDUNG 1', dbField: 'pekerjaan_saudara_kandung_1' },
    { excelHeader: 'KETERANGAN SAUDARA KANDUNG 1', dbField: 'keterangan_saudara_kandung_1' },
    { excelHeader: 'NAMA SAUDARA KANDUNG 2', dbField: null },
    { excelHeader: 'JENIS KELELAMIN SAUDARA KANDUNG 2', dbField: null },
    { excelHeader: 'TANGGAL LAHUR SAUDARA KANDUNG 2', dbField: null },
    { excelHeader: 'PENDIDIKAN TERAKHIR SAUDARA KANDUNG 2', dbField: null },
    { excelHeader: 'PEKERJAAN SAUDARA KANDUNG 2', dbField: null },
    { excelHeader: 'KETERANGAN SAUDARA KANDUNG 2', dbField: null },
    { excelHeader: 'NAMA SAUDARA KANDUNG 3', dbField: null },
    { excelHeader: 'JENIS KELELAMIN SAUDARA KANDUNG 3', dbField: null },
    { excelHeader: 'TANGGAL LAHUR SAUDARA KANDUNG 3', dbField: null },
    { excelHeader: 'PENDIDIKAN TERAKHIR SAUDARA KANDUNG 3', dbField: null },
    { excelHeader: 'PEKERJAAN SAUDARA KANDUNG 3', dbField: null },
    { excelHeader: 'KETERANGAN SAUDARA KANDUNG 3', dbField: null },
    { excelHeader: 'NAMA SAUDARA KANDUNG 3', dbField: null },
    { excelHeader: 'JENIS KELELAMIN SAUDARA KANDUNG 3', dbField: null },
    { excelHeader: 'TANGGAL LAHUR SAUDARA KANDUNG 3', dbField: null },
    { excelHeader: 'PENDIDIKAN TERAKHIR SAUDARA KANDUNG 3', dbField: null },
    { excelHeader: 'PEKERJAAN SAUDARA KANDUNG 3', dbField: null },
    { excelHeader: 'KETERANGAN SAUDARA KANDUNG 3', dbField: null },
    { excelHeader: 'NAMA SAUDARA KANDUNG 4', dbField: null },
    { excelHeader: 'JENIS KELELAMIN SAUDARA KANDUNG 4', dbField: null },
    { excelHeader: 'TANGGAL LAHUR SAUDARA KANDUNG 4', dbField: null },
    { excelHeader: 'PENDIDIKAN TERAKHIR SAUDARA KANDUNG 4', dbField: null },
    { excelHeader: 'PEKERJAAN SAUDARA KANDUNG 4', dbField: null },
    { excelHeader: 'KETERANGAN SAUDARA KANDUNG 4', dbField: null },
    { excelHeader: 'SIKLUS PEMBAYARAN', dbField: null },
    { excelHeader: 'NAMA BANK', dbField: 'nama_bank' },
    { excelHeader: 'CABANG BANK', dbField: 'cabang_bank' },
    { excelHeader: 'NAMA BAPAK MERTUA', dbField: 'nama_ayah_mertua' },
    { excelHeader: 'TANGGAL LAHUR BAPAK MERTUA', dbField: 'tanggal_lahir_ayah_mertua' },
    { excelHeader: 'PENDIDKAN TERAKHIR BAPAK MERTUA', dbField: 'pendidikan_terakhir_ayah_mertua' },
    { excelHeader: 'PEKERJAAN BAPAK MERTUA', dbField: 'pekerjaan_ayah_mertua' },
    { excelHeader: 'KETERANGAN BAPAK MERTUA', dbField: 'keterangan_ayah_mertua' },
    { excelHeader: 'NAMA IBU MERTUA', dbField: 'nama_ibu_mertua' },
    { excelHeader: 'TANGGAL LAHIR IBU MERTUA', dbField: 'tanggal_lahir_ibu_mertua' },
    { excelHeader: 'PENDIDIKAN TERAKHIR IBU MERTUA', dbField: 'pendidikan_terakhir_ibu_mertua' },
    { excelHeader: 'PEKERJAAN IBU MERTUA', dbField: 'pekerjaan_ibu_mertua' },
    { excelHeader: 'KETERANGAN IBU MERTUA', dbField: 'keterangan_ibu_mertua' },
    { excelHeader: 'ORGANISSASI SUB DEPARTMENT', dbField: null },
    { excelHeader: 'DEPARTMENT', dbField: 'department' },
    { excelHeader: 'DIVISI', dbField: 'divisi' },
    { excelHeader: 'NAMA KONTAK DARURAT 1', dbField: 'nama_kontak_darurat_1' },
    { excelHeader: 'HUNGAN KONTRAK DARURAT 1', dbField: 'hubungan_kontak_darurat_1' },
    { excelHeader: 'ALAMAT KONTAK DARURAT 1', dbField: 'alamat_kontak_darurat_1' },
    { excelHeader: 'NOMOR HP1 KONTAK DARURAT 1', dbField: 'nomor_telepon_kontak_darurat_1' },
    { excelHeader: 'NOMOR HP2 KONTAK DARURAT 1', dbField: 'nomor_telepon_kontak_darurat_2' },
    { excelHeader: 'UKURAN SEPATU', dbField: 'ukuran_sepatu_kerja' },
    { excelHeader: 'UKURAN BAJU', dbField: 'ukuran_seragam_kerja' },
    { excelHeader: 'LOKASI SEBELUMNYA', dbField: 'lokasi_sebelumnya' },
    { excelHeader: 'TANGGAL MUTASI', dbField: 'tanggal_mutasi' },
    { excelHeader: 'UNIT YANG DI BAWAH', dbField: null },
    { excelHeader: 'POINT OF ORIGINAL', dbField: 'point_of_original' },
    { excelHeader: 'POINT OF HIRE', dbField: 'point_of_hire' },
    { excelHeader: 'NOMOR KARTU KELUARGA', dbField: 'nomor_kartu_keluarga' },
    { excelHeader: 'NOMOR NIK KK', dbField: 'no_nik_kk' },
    { excelHeader: 'LOKASI KERJA', dbField: 'lokasi_kerja' },
    { excelHeader: 'STATUS KARYAWAN', dbField: 'status_karyawan' },
    { excelHeader: 'TAG', dbField: 'tag' },
    { excelHeader: 'MANAGER', dbField: 'manager' },
    { excelHeader: 'ATASAN LANGSUNG', dbField: 'atasan_langsung' },
    { excelHeader: 'EMAIL PERUSAHAAN', dbField: 'email_perusahaan' },
    { excelHeader: 'EMAIL PRIBADI', dbField: 'email_pribadi' },
];

export const MASTER_MAPPING: MasterMapping[] = [
    { excelHeader: 'PANGKAT KATEGORI', masterField: 'nama kategori pangkat' },
    { excelHeader: 'GOLONGAN', masterField: 'nama golongan' },
    { excelHeader: 'SUB GOLONGAN', masterField: 'nama sub golongan' },
    { excelHeader: 'JENIS HUBUNGAN KERJA', masterField: 'nama jenis hubungan kerja' },
    { excelHeader: 'TAG', masterField: 'nama tag' },
    { excelHeader: 'LOKASI KERJA', masterField: 'nama lokasi kerja' },
    { excelHeader: 'STATUS KARYAWAB', masterField: 'nama status' },
    { excelHeader: 'DIVISI', masterField: 'nama divisi' },
    { excelHeader: 'DEPARTMENT', masterField: 'nama departmen' },
    { excelHeader: 'POSISI JABATAN (MASTER)', masterField: 'nama posisi jabatan' },
];
